### ISSUE TITLE
Hi, help?

### ISSUE THREAD

**Issue by liamcoded** [denisk20/programmer-dvorak#8]
I've cloned the repo, and did git submodule update --init. But all I get is : 
`fatal: Not a git repository (or any of the parent directories): .git`
Also, the website shows in a browser but checking what's typed doesn't work.

I am trying to set it up so it runs on my laptop once I turn off internet connection, it's for productivity reasons. 

Could you help me out?

**Comment by denisk20** [comment]
Hi, are you running `git submodule update --init` from the root directory of the cloned project? Once you fetch the submodule you should be able to work offline.

**Comment by liamcoded** [comment]
Thank you  for the quick response. 
Just ran it here
`/Documents/programmer-dvorak-master/programmer-dvorak`
It seems to have worked. But then I open the index file, from webapp folder, in Chrome and it still doesn't work.

**Comment by denisk20** [comment]
What exactly doesn't work? Can you see the index page in the browser? You should see something like this
![image](https://cloud.githubusercontent.com/assets/3080318/22198605/e8eb799c-e15f-11e6-98f3-9575f3f8b1f6.png)

Can you navigate to the individual lessons from there? After you update submodules you should see the output similar to this:
```
denisk@denisk-kubuntu:~/programmer-dvorak$ git submodule update --init
Submodule 'war/js/typingtutor' (git@github.com:denisk20/TypingTutor.git) registered for path 'src/main/webapp/js/typingtutor'
Cloning into '/home/denisk/programmer-dvorak/src/main/webapp/js/typingtutor'...
Submodule path 'src/main/webapp/js/typingtutor': checked out 'fda7eb7dee222b54d2fe07afcac3f1a0eba2a942'
```
After that, the lessons should work offline:

![image](https://cloud.githubusercontent.com/assets/3080318/22198637/0d9442ba-e160-11e6-932d-7ba56c00c772.png)

One note: if you have _downloaded sources_ instead of _cloning_ the repo then it won't work, because github doesn't bundle submodule projects this way. You need to clone the project by running `git clone git@github.com:denisk20/programmer-dvorak.git` and fetch submodules.
You could of course download the sources of TypingTutor subproject manually and copy them to `src/main/webapp/js/typingtutor` directory but it's much more work than cloning the repo and fetching submodules.

**Comment by liamcoded** [comment]
Problem solved. It was my fault. After updating submodules I kept opening the wrong copy of the project. 
Thank you very much for creating this cool project. And thank you for your time and patience.

**Comment by denisk20** [comment]
Glad that you solved it!
